### DISCUSSION TITLE
Ability to add custom MediaTypes to search buttons

### DISCUSSION THREAD

**Discussion by peteS-UK** [antontanderup/mediocre-hass-media-player-cards#69] [Ideas]
Currently, you've got the standard MediaTypes as search options - Albums, Artists etc..  Different integrations will extend this list with their own extras.  For example, in Squeezebox, I'd like to add genres, album artists and favorites.  It would be great to have an option to extend the default list.

**Comment by antontanderup** [comment]
I think ideally I would have a default set and then you can pick your integration and based on that the card picks the right extras. Wouldn’t be too tough to maintain I think.

**Comment by peteS-UK** [comment]
Fair enough - as you say, the list of common integrations isn't that large, and not all will extend the list.  I'd add Genres to your current, standard, list then for LMS add Album Artists and Favorites.  For Sonos, certainly Favorites.

You could look at the top level of async_browse_media.  That would actually give you a dynamic list and the associated media_content_type.  If you just do async_browse_media with no type specified, you'll get the top level, which for squeezebox will be

```yaml
 children:
    - title: Favorites
      media_class: track
      media_content_type: favorites
      media_content_id: favorites
      children_media_class: null
      can_play: false
      can_expand: true
      can_search: false
      thumbnail: null
    - title: Artists
      media_class: artist
      media_content_type: artists
      media_content_id: artists
      children_media_class: null
      can_play: true
      can_expand: true
      can_search: false
      thumbnail: null
    - title: Albums
      media_class: album
      media_content_type: albums
      media_content_id: albums
      children_media_class: null
      can_play: true
      can_expand: true
      can_search: false
      thumbnail: null
    - title: Tracks
      media_class: track
      media_content_type: tracks
      media_content_id: tracks
      children_media_class: null
      can_play: true
      can_expand: true
      can_search: false
      thumbnail: null
    - title: Playlists
      media_class: playlist
      media_content_type: playlists
      media_content_id: playlists
      children_media_class: null
      can_play: true
      can_expand: true
      can_search: false
      thumbnail: null
    - title: Genres
      media_class: genre
      media_content_type: genres
      media_content_id: genres
      children_media_class: null
      can_play: true
      can_expand: true
      can_search: false
      thumbnail: null
    - title: New Music
      media_class: album
      media_content_type: new music
      media_content_id: new music
      children_media_class: null
      can_play: true
      can_expand: true
      can_search: false
      thumbnail: null
    - title: Album Artists
      media_class: artist
      media_content_type: album artists
      media_content_id: album artists
      children_media_class: null
      can_play: true
      can_expand: true
      can_search: false
      thumbnail: null
    - title: Apps
      media_class: app
      media_content_type: apps
      media_content_id: apps
      children_media_class: null
      can_play: false
      can_expand: true
      can_search: false
      thumbnail: null
    - title: Radios
      media_class: app
      media_content_type: radios
      media_content_id: radios
      children_media_class: null
      can_play: false
      can_expand: true
      can_search: false
      thumbnail: null
    - title: Camera
      media_class: app
      media_content_type: app
      media_content_id: media-source://camera
      children_media_class: null
      can_play: false
      can_expand: true
      can_search: false
      thumbnail: https://brands.home-assistant.io/_/camera/logo.png
    - title: DLNA Servers
      media_class: app
      media_content_type: app
      media_content_id: media-source://dlna_dms
      children_media_class: null
      can_play: false
      can_expand: true
      can_search: false
      thumbnail: https://brands.home-assistant.io/_/dlna_dms/logo.png
    - title: Image Upload
      media_class: app
      media_content_type: app
      media_content_id: media-source://image_upload
      children_media_class: null
      can_play: false
      can_expand: true
      can_search: false
      thumbnail: https://brands.home-assistant.io/_/image_upload/logo.png
    - title: My media
      media_class: app
      media_content_type: app
      media_content_id: media-source://media_source
      children_media_class: null
      can_play: false
      can_expand: true
      can_search: false
      thumbnail: https://brands.home-assistant.io/_/media_source/logo.png
    - title: Nest
      media_class: app
      media_content_type: app
      media_content_id: media-source://nest
      children_media_class: null
      can_play: false
      can_expand: true
      can_search: false
      thumbnail: https://brands.home-assistant.io/_/nest/logo.png
    - title: Text-to-speech
      media_class: app
      media_content_type: app
      media_content_id: media-source://tts
      children_media_class: null
      can_play: false
      can_expand: true
      can_search: false
      thumbnail: https://brands.home-assistant.io/_/tts/logo.png
```

If you exclude anything with media_content_id starting with media-source, that'll give you a pretty good list.  Sadly, can_search isn't implemented yet, so you can't use that for anything clever.

**Comment by antontanderup** [comment]
Just had an idea based on your suggestion of just letting your define your own media types for search. Basically let you define it manually but let the visual editor help by having the option of pregenerating types (using a call to media browser).
My main gripe with manually adding a list of things in the config is that it’s a pain, but if it’s just pressing a button and then potentially removing some options that’s much simpler.
That way we just have some simple defaults like now, with the option of overriding.

(Also just posting here so I don’t forget it)

**Reply by antontanderup** [reply]
Expanding on this later on would be showing media browser content when you select a filter, but haven’t typed a search query.

**Reply by peteS-UK** [reply]
Yep.  If you just use 

```yaml
action: media_player.browse_media
target:
  device_id: xxxxxx
data: {}
```

to get the top level list from the media browser of media_content_type from children[], discard anything with media_content_id starting with media-source and then use this to populate a multi select list, that would be ideal and would give you favorites in the list.

In the future I do think it's worth having the option to manually add to this list as well.  It would be great to be able to search, say, qobuz, but that won't work on the search side atm with squeezebox.  With apps and radios, we actually dynamically create some media types e.g. qobuz, tidal etc.) as we browse the hierarchy.  I don't support searching it yet - need to look if i can make it work at some point.
