### DISCUSSION TITLE
Show Massive Media Player Card on tab of a button

### DISCUSSION THREAD

**Discussion by jonassmets** [antontanderup/mediocre-hass-media-player-cards#76] [Q&A] [answered]
Hi! First of all, the integration is amazing! I love the way everything comes together. I tried every other card out there. This one fits my needs the best! Now I'm building a new dashboard, and I want to create simple cards with icons. Pressing a card needs to pull up the Massive Media Player Card? In the Massive Media Player Card I think I should be able to control everything like volume and grouping? Is this possible? Thanks. Jonas

**Comment by antontanderup** [comment, marked as answer]
Currently the only way to use the built in popup is through the regular (not massive) card.
What you can do, which I’ve seen others do, is use the massive card in a bubble card popup.

**Comment by jonassmets** [comment]
@antontanderup are there any examples around? I can't get it to work with the bubble card?

**Reply by antontanderup** [reply]
https://github.com/antontanderup/mediocre-hass-media-player-cards/discussions/55#discussioncomment-13177380
But there's no yaml so you would have to ask @mooseBringer :)

**Reply by mooseBringer** [reply]
@jonassmets Hi!

What is it that is not working? Here's some of my yaml for the pop-up, if you use music assistant do a replace all on ```koksradio_ma``` with your MA player. Otherwise we will have to replace the separator buttons. 

```
tap_action:
  action: navigate
  navigation_path: "#media"
```

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#media"
    name: Köksradion
    icon: mdi:radio
    button_type: name
    modules:
      - default
    show_header: false
    margin_top_mobile: "-56px"
  - type: custom:bubble-card
    card_type: separator
    modules:
      - default
    name: ""
    sub_button:
      - icon: mdi:album
        tap_action:
          action: url
          url_path: http://192.168.0.10:8095/#/albums?player=köksradio_ma&frameless=true
      - icon: mdi:account-music-outline
        tap_action:
          action: url
          url_path: >-
            http://192.168.0.10:8095/#/artists?player=köksradio_ma&frameless=true
      - icon: mdi:playlist-music-outline
        tap_action:
          action: url
          url_path: >-
            http://192.168.0.10:8095/#/playlists?player=köksradio_ma&frameless=true
      - icon: mdi:magnify
        tap_action:
          action: url
          url_path: http://192.168.0.10:8095/#/search?player=köksradio_ma&frameless=true
      - icon: mdi:motion-play-outline
        tap_action:
          action: url
          url_path: >-
            http://192.168.0.10:8095/#/home?showFullscreenPlayer=true?player=köksradio_ma
      - icon: mdi:close
        tap_action:
          action: navigate
          navigation_path: "#"
    icon: mdi:radio
  - type: custom:mediocre-massive-media-player-card
    entity_id: media_player.koksradio_ma
    mode: in-card
    use_art_colors: true
    ma_entity_id: media_player.koksradio_ma
    custom_buttons:
      - icon: mdi:power
        name: Power
        tap_action:
          action: toggle
    search:
      enabled: true
      entity_id: media_player.koksradio_ma
```

![Screenshot_20250531_082237_Home Assistant.jpg](https://github.com/user-attachments/assets/189cab16-1ab7-44aa-b627-4f2e94104deb)
