### ISSUE TITLE
Feature Request: Populate ma_entity_id via template

### ISSUE THREAD

**Issue by Scags104** [antontanderup/mediocre-hass-media-player-cards#106]
To decrease code I can use this with either auto-entities or with streamline-card. Works great with one exception, i can't programmatically set the ma_entity_id. In my use case the entities are this.entity_id + "_ma" but this doesn't seem to work. Do you think it would be possible to have this field accept templates?

Eample
```
ma_entity_id: | 
    {{this.entity_id + "_ma"}}
```

Not holding my breath as this is a super minimal use case but if its something you could add it would be appreciated!

Thanks, the card is awesome.

**Comment by antontanderup** [comment]
You can do it with streamline. That’s what I do as well. I’ll paste part of my streamline player card below, that might help:
```
player_card:
    default:
      - media_player_core_name: antons_office
      - media_player_name: Antons Office
    card:
      type: custom:mediocre-media-player-card
      entity_id: media_player.[[media_player_core_name]]_universal
      search:
        enabled: true
        entity_id: media_player.[[media_player_core_name]]_lms
        show_favorites: true
```

**Comment by Scags104** [comment]
fun update. was able to use streamline-card to also populate standard and MA media players based on what is playing. This way whether its triggered by google home or MA the images and details always show in the player

```
player_card:
  card:
    type: custom:mediocre-media-player-card
    tap_opens_popup: true
    entity_id_javascript: |
      return `${states['[[media_player_name]]'].attributes.media_title  === 'Music Assistant' ? ('[[media_player_name]]' + '_ma') : '[[media_player_name]]'}`
    mode: in-card
    card_mod:      
      class: soft-ui
    action: {}
    options:
      always_show_power_button: true
    search:
      enabled: true
      entity_id_javascript: |
        return  "[[media_player_name]]_ma" 
      show_favorites: true
```
