### ISSUE TITLE
Layout data lost when editing card

### ISSUE THREAD

**Issue by Dieghito72** [antontanderup/mediocre-hass-media-player-cards#107]
Hi, I'm using  version 0.22.0-beta5 (to benefit of new _always_show_custom_buttons_ setting) and setup the card with using the layout options **columns: full**:

![Image](https://github.com/user-attachments/assets/a55f6052-add4-4e73-a0e9-14c5ac24fad9)

This setting is correctly saved:

```yaml
type: custom:mediocre-media-player-card
entity_id: media_player.home_assistant_voice_0916bc_media_player_2
action: {}
ma_entity_id: media_player.home_assistant_voice_0916bc_media_player_2
custom_buttons:
  - name: Virgin radio
    icon: mdi:radio
    tap_action:
      action: perform-action
      perform_action: music_assistant.play_media
      target:
        entity_id: media_player.home_assistant_voice_0916bc_media_player_2
      data:
        media_id: Virgin radio Italia
        media_type: radio
  - name: Radio Deejay
    icon: mdi:radio
    tap_action:
      action: perform-action
      perform_action: music_assistant.play_media
      target:
        entity_id: media_player.home_assistant_voice_0916bc_media_player_2
      data:
        media_id: Radio Deejay
        media_type: radio
options:
  always_show_custom_buttons: true
grid_options:
  columns: full
```

But if edit the card again the settings is missing, only settings from the card are correctly "loaded":

```yaml
type: custom:mediocre-media-player-card
entity_id: media_player.home_assistant_voice_0916bc_media_player_2
action: {}
ma_entity_id: media_player.home_assistant_voice_0916bc_media_player_2
custom_buttons:
  - name: Virgin radio
    icon: mdi:radio
    tap_action:
      action: perform-action
      perform_action: music_assistant.play_media
      target:
        entity_id: media_player.home_assistant_voice_0916bc_media_player_2
      data:
        media_id: Virgin radio Italia
        media_type: radio
  - name: Radio Deejay
    icon: mdi:radio
    tap_action:
      action: perform-action
      perform_action: music_assistant.play_media
      target:
        entity_id: media_player.home_assistant_voice_0916bc_media_player_2
      data:
        media_id: Radio Deejay
        media_type: radio
options:
  always_show_custom_buttons: true
```
